version: "3.4"
services:
  redis:
    restart: always
    image: redis:3.2
  db:
    restart: always
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
  web:
    restart: always
    labels:
      - "neos"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
      - "traefik.docker.network=main"
      - "traefik.frontend.rule=Host:kp-f.ru,www.kp-f.ru"
    volumes:
      - /data/www-provisioned/Web/_Resources
    image: ghcr.io/psmb/kpfdistr:master
    hostname: kpfru
    networks:
      - default
      - main
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - '80'
    depends_on:
      - db
      - redis
volumes:
  db-data:
networks:
  main:
    external:
      name: main

