redis:
  image: redis:3.2

db:
  image: mariadb:10.3
  restart: always
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: db
    MYSQL_USER: admin
    MYSQL_PASSWORD: pass

web:
  image: dimaip/docker-neos-alpine:latest
  ports:
    - '80'
    - '1125:22'
  links:
    - db
    - redis
  volumes:
    - /data
  environment:
    - PHP_TIMEZONE=Europe/Moscow
    - REPOSITORY_URL=https://github.com/psmb/KpfDistr
    - VIRTUAL_HOST=kp-f.ru,dev.kp-f.ru,next.kp-f.ru,www.kp-f.ru
    - LETSENCRYPT_HOST=kp-f.ru,dev.kp-f.ru,www.kp-f.ru
    - LETSENCRYPT_EMAIL=dimaip@gmail.com
    - IMPORT_GITHUB_PUB_KEYS=dimaip
    - AWS_ENDPOINT=https://hb.bizmrg.com
    - AWS_BACKUP_ARN=s3://psmb-neos-resources/db/kpf/
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
