TYPO3:
  Flow:
    i18n:
      defaultLocale: 'ru'
    http:
      baseUri: 'https://kp-f.ru/'
  Neos:
    typoScript:
      autoInclude:
        'Sfi.Site': TRUE
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen marginVertical-double'
