
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen marginVertical-double'
Neos:
  Flow:
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://kp-f.ru/'
    resource:
      collections:
        persistent:
          storage: s3PersistentResourcesStorage
          target: s3PersistentResourcesTarget
      storages:
        s3PersistentResourcesStorage:
          storage: 'Flownative\Aws\S3\S3Storage'
          storageOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'storage/kpf/'
      targets:
        s3PersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'target/kpf/'
            baseUri: 'https://psmb-neos-resources.hb.bizmrg.com/target/kpf/'
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
    fusion:
      autoInclude:
        Sfi.Site: true
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: '%env:AWS_ACCESS_KEY_ID%'
            secret: '%env:AWS_SECRET_ACCESS_KEY%'
          endpoint: 'https://hb.bizmrg.com'
