
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen paddingVertical-double'
Neos:
  Flow:
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://kp-f.ru/'
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
    fusion:
      autoInclude:
        Sfi.Site: true
