
TYPO3:
  Neos:
    typoScript:
      autoInclude:
        Sfi.Site: true
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen marginVertical-double'
Neos:
  Flow:
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://kp-f.ru/'
