
Sfi:
  YouTube:
    className: 'YouTube flex-video widescreen marginVertical-double'
Neos:
  Flow:
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://kp-f.ru/'
    error:
      exceptionHandler:
        className: 'Yeebase\Graylog\Error\GraylogExceptionHandler'
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
    fusion:
      autoInclude:
        Sfi.Site: true
Yeebase:
  Graylog:
    host: '172.17.42.1'
    port: 12201
    chunksize: 'wan'
